development:
  adapter: postgresql
  encoding: unicode
  database: ecommerce_challenge_development
  pool: 5
  username: jkm
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: ecommerce_challenge_test
  pool: 5
  username: jkm
  password: password